---
- hosts: localhost
  become: yes
  tasks:
  - name: Update packages
    apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: Install packages
    apt:
      name:
        - cdebootstrap
  - name: Download latest distrod image
    ansible.builtin.get_url:
      url: "https://github.com/nullpo-head/wsl-distrod/releases/latest/download/opt_distrod.tar.gz"
      dest: /tmp/opt_distrod.tar.gz
